import './globals.css'
import { Open_Sans } from 'next/font/google'

import Navbar from "app/(shared)/Navbar";
import Footer from "app/(shared)/Footer"

const open_sans = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Blog AI APP',
  description: 'Blog auto generated by AI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
        <Navbar />  
        {children}
        <Footer />
      
      </body>
    </html>
  )
}
